# Configuration file for all scripts
# All file paths are relative to the parent script directory, unless otherwise stated
---
global-variables:
  network-variables:
    # Path to the configuration files for the networks
    - &network_configs_directory '../network_configs/'
    # File name for the network model to load
    - &network 'network_v8'
    - &encoder 'network_v8_encoder'
    - &reduced_network 'network_v10'
    - &reduced_encoder 'network_v10_encoder'
  data-variables:
    # Path to the images with lensing and X-ray maps and parameters
    - &data_dir '../data/'
    - &data_path '../data/gaussian_data_1.pkl'
  output-variables:
    # Directory to save network training states
    - &network_states_directory '../model_states/'
    - &plots-directory '../plots/'

# main.py config file
main:
  # Variables for training the network
  training:
    # Number of epochs to train the network for
    epochs: 150
    # Number of inputs to process between network weight updates
    batch-size: 120
    # File number to save the network progres
    network-save: 0
    # File number to load the network state
    network-load: 0
    # Learning rate for training the network
    learning-rate: 1.0e-5
    # Maximum learning rate for training the network if using OneCycleLR
    max-learning-rate: 1.0e-3
    # Validation dataset fraction
    validation-fraction: 0.2
    # File name for network model to load
    network-name: *reduced_network
    # Network description
    description: 'Mix Up - No CDM - BAHAMAS-0.3 Unknown - OneCycleLR'
    # Known simulations
    known:
#      - 'bahamas_cdm'
#      - 'bahamas_cdm_low'
#      - 'bahamas_cdm_hi'
      - 'bahamas_0.03_mix'
      - 'bahamas_0.1'
      - 'bahamas_0.17_mix'
#      - 'bahamas_0.3'
      - 'bahamas_0.55_mix'
#      - 'bahamas_dmo_1'
      - 'bahamas_1'
#      - 'flamingo'
#      - 'flamingo_low'
#      - 'flamingo_hi'
#      - 'bahamas_dmo_cdm'
#      - 'darkskies_cdm'
#      - 'darkskies_0.1'
#      - 'darkskies_0.2'
    # Unknown simulations
    unknown:
#      - 'bahamas_0.1'
      - 'bahamas_0.3'
#      - 'flamingo_low_test'
#      - 'bahamas_dmo_0.1'
#      - 'noise'
#      - 'tng'
#      - 'darkskies_0.1'
#      - 'bahamas_cdm_low'
#      - 'bahamas_cdm_hi'
  # File location for different datasets
  data:
    # Path to the list containing the images and parameters
    data-dir: *data_dir
    # Path to the configuration files for the encoder and decoder
    network-configs-directory: *network_configs_directory
  # Directory locations for the different outputs
  output:
    # Directory to save network training states
    network-states-directory: *network_states_directory
    # Path to the parameters predictions generated by the network
    predictions-path: '../data/parameter_predictions.pkl'
    # Path to the parameter distributions generated by the flow
    distributions-path: '../data/parameter_distributions.pkl'
    # Directory to save plots
    plots-directory: *plots-directory
# batch_train.py config file
batch-train:
  # File location for different datasets
  data:
    # Path to the configuration directory for batch training
    config-dir: '../batch_train_configs/'
    # Name of the batch train configuration file
    config: 'final_nets'
#    config: 'effective_cross_section'
#    config: 'final_choices_regression'
    # Path to the list containing the images and parameters
    data-dir: *data_dir
  # Paths and directory locations for saving outputs
  output:
    # Directory to save the results
    batch-train-dir: '../data/'
# optimise.py and hyperparam_search.py config file
optimise:
  # Variables for optimising the network
  optimisation:
    # Number of epochs to train the network for
    epochs: 2
    # Number of trials to run
    trials: 50
    # File number to save the network progres
    network-save: 0
    # File number to load the network state
    network-load: 0
    # File number to save the study progres
    study-save: 8
    # File number to load the study state
    study-load: 0
    # Number of epochs before pruning can occur
    warmup: 10
    # Number of epochs to average over when reporting metrics
    smooth-number: 5
    # Learning rate for training the network
    learning-rate: 1.0e-3
    # File name for network model to load
    network-name: *reduced_network
  # File locations for optimisation
  data:
    # Path to the directory for studies
    study-directory: *data_dir
    # Simulations to train on
    simulations:
      -
        - 'bahamas_cdm'
        - 'bahamas_0.1'
        - 'bahamas_0.3'
        - 'bahamas_1'
      -
        - 'bahamas_cdm_low'
        - 'bahamas_cdm_hi'
      -
        - 'darkskies_cdm'
        - 'darkskies_0.1'
        - 'darkskies_0.2'
  # Paths and directory locations for saving outputs
  output:
    # Path to save the base network object
    base-network: '../data/base_net.pth'
    # Path to save the network during training
    network: '../data/optuna_net.pth'
    # Path to the directory to save plots
    plots-directory: *plots-directory
# gaussian_tests.py config file
gaussian:
  # Variables for the Gaussian tests
  gaussian:
    # Clears existing Gaussian tests
    clear: True
    # Number of epochs to train the network for
    epochs: 100
    # Number of runs to do per test
    runs: 5
    # Number of inputs to process between network weight updates
    batch-size: 120
    # Validation dataset fraction
    validation-fraction: 0.15
    # Names of the tests
    names:
      - '2 Anchors'
      - '3 Anchors'
      - '4 Anchors'
    # Classes that are known for each test
    known:
      -
        - 0.05
        - 1.05
      -
        - 0.05
        - 0.5
        - 1.05
      -
        - 0.05
        - 0.3
        - 0.7
        - 1.05
    # Classes that are known but the label is unknown
    unknown:
      - []
  # File locations for Gaussian tests
  data:
    data-path: '../data/gaussian_data_3_less_noise.pkl'
  # Paths and directory locations for saving outputs
  output:
    # Path to save the outputs from the Gaussian tests
    tests-path: '../data/gaussian_tests.pkl'
    # Path to the directory to save plots
    plots-directory: *plots-directory
